<?php


namespace App\Enums;

use App\Utils\BaseEnum;

class PermissionEnum extends BaseEnum
{
    const ADD_ORG_INFO = 'ADD_ORG_INFO';

    const ADD_ORG_STRUCTURE = 'ADD_ORG_STRUCTURE';

    const UPLOAD_ORG_STAFF = 'UPLOAD_ORG_STAFF';

    const START_NEW_FINANCIAL_YEAR = 'START_NEW_FINANCIAL_YEAR';

    const UPLOAD_STRATEGIC_PILLARS = 'UPLOAD_STRATEGIC_PILLARS';

    const SET_MISSION_STATEMENT = 'SET_MISSION_STATEMENT';

    const CREATE_STATEGIC_INTENT = 'CREATE_STATEGIC_INTENT';

    const CREATE_SPECIFIED_TASK = 'CREATE_SPECIFIED_TASK';

    const CREATE_IMPLIED_TASK = 'CREATE_IMPLIED_TASK';

    const SET_BOUNDARY = 'SET_BOUNDARY';

    const APPROVE_IMPLIED_TASK = 'APPROVE_IMPLIED_TASK';

    const UPLOAD_MISSION_PLAN = 'UPLOAD_MISSION_PLAN';

    const APPROVE_MISSION_PLAN = 'APPROVE_MISSION_PLAN';

    const UPDATE_TASK_PROGRESS = 'UPDATE_TASK_PROGRESS';

    const UPDATE_SUCCESS_PROGRESS = 'UPDATE_SUCCESS_PROGRESS';

    const ADD_STAFF_MISSION_PLAN = 'ADD_STAFF_MISSION_PLAN';
}
