<?php


namespace App\Enums;

use App\Utils\BaseEnum;

class PermissionEnum extends BaseEnum
{
    const ADD_ORG_INFO = 'ADD_ORG_INFO';
    const VIEW_ORG_INFO = 'VIEW_ORG_INFO';
    const EDIT_ORG_INFO = 'EDIT_ORG_INFO';
    const DELETE_ORG_INFO = 'DELETE_ORG_INFO';

    const ASSIGN_ROLE = 'ASSIGN_ROLE';
    const DETACH_ROLE = 'DETACH_ROLE';
    const ASSIGN_PERMISSION = 'ASSIGN_PERMISSION';
    const DETACH_PERMISSION = 'DETACH_PERMISSION';

    const VIEW_PERMISSIONS = 'VIEW_PERMISSIONS';
    const VIEW_ROLES = 'VIEW_ROLES';

    const VIEW_ORG_STRUCTURE = 'VIEW_ORG_STRUCTURE';
    const ADD_ORG_STRUCTURE = 'ADD_ORG_STRUCTURE';

    const ADD_ORG_SETUP = 'ADD_ORG_SETUP';
    const VIEW_ORG_SETUP = 'VIEW_ORG_SETUP';
    const EDIT_ORG_SETUP = 'EDIT_ORG_SETUP';
    const DELETE_ORG_SETUP = 'DELETE_ORG_SETUP';

    const UPLOAD_ORG_STAFF = 'UPLOAD_ORG_STAFF';
    const UPLOAD_ORG_SETUP = 'UPLOAD_ORG_SETUP';
    const UPLOAD_ORG_JOB_DESC = 'UPLOAD_ORG_JOB_DESC';

    const ADD_ORG_STAFF = 'ADD_ORG_STAFF';
    const VIEW_ORG_STAFF = 'VIEW_ORG_STAFF';
    const EDIT_ORG_STAFF = 'EDIT_ORG_STAFF';
    const DELETE_ORG_STAFF = 'DELETE_ORG_STAFF';

    const START_NEW_FINANCIAL_YEAR = 'START_NEW_FINANCIAL_YEAR';
    const UPLOAD_STRATEGIC_PILLARS = 'UPLOAD_STRATEGIC_PILLARS';
    const SET_MISSION_STATEMENT = 'SET_MISSION_STATEMENT';
    const CREATE_STATEGIC_INTENT = 'CREATE_STATEGIC_INTENT';
    const CREATE_SPECIFIED_TASK = 'CREATE_SPECIFIED_TASK';
    const CREATE_IMPLIED_TASK = 'CREATE_IMPLIED_TASK';
    const SET_BOUNDARY = 'SET_BOUNDARY';
    const APPROVE_IMPLIED_TASK = 'APPROVE_IMPLIED_TASK';
    const UPLOAD_MISSION_PLAN = 'UPLOAD_MISSION_PLAN';
    const APPROVE_MISSION_PLAN = 'APPROVE_MISSION_PLAN';
    const UPDATE_TASK_PROGRESS = 'UPDATE_TASK_PROGRESS';
    const UPDATE_SUCCESS_PROGRESS = 'UPDATE_SUCCESS_PROGRESS';
    const ADD_STAFF_MISSION_PLAN = 'ADD_STAFF_MISSION_PLAN';
}
